
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from math import floor
import tkinter as tk
from tkinter import *
from turtle import update
import requests
import geocoder
import time
import json
from datetime import datetime
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1035x665")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 665,
    width = 1035,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

def get_Weather():
        g = geocoder.ip('me')
        cordinates = g.latlng
        global geo_position
        geo_position = cordinates
        api_key = "8a7a7bedb7f79d4e68c2405b11725a61"
        lat = cordinates[0]
        lon = cordinates[1]
        url1 = "https://api.openweathermap.org/data/2.5/onecall?lat=%s&lon=%s&appid=%s&units=metric" % (lat, lon, api_key)
        response = requests.get(url1)
        data = json.loads(response.text)
        global data1
        data1 = data

def update_clock():
        hours=time.strftime("%I")
        minutes=time.strftime("%M")
        am_or_pm=time.strftime("%p")
        time_text=hours+":"+minutes+" "+am_or_pm
        digital_clock_lbl.config(text=time_text)
        digital_clock_lbl.after(100,update_clock)#after every 100 milli seconds the clock will be updated

def update_weather_desc():
    weather_desc_data.config(text=data1["current"]["weather"][0]["main"].title())
    weather_desc_data.after(100,update_weather_desc)

def update_date():
    date = datetime.now()
    text1 = f"{date:%d / %m / %Y\n%A}"
    date_time_lbl.config(text=text1)
    date_time_lbl.after(100,update_date)

def update_wind_speed():
    wind_speed_data.config(text=str(data1["current"]["wind_speed"]) + " meter/sec")
    wind_speed_data.after(100,update_wind_speed)

def update_humidity():
    humidity_data.config(text=str(data1["current"]["humidity"]) + " %")
    humidity_data.after(100,update_humidity)

def update_pressure():
    pressure_data.config(text=str(data1["current"]["pressure"]) + " hPa")
    pressure_data.after(100,update_pressure)

def update_uvi():
    uvi_data.config(text=data1["current"]["uvi"])
    uvi_data.after(100,update_uvi)

def update_dewpoint():
    dew_point_data.config(text=str(data1["current"]["dew_point"]) + " C")
    dew_point_data.after(100,update_dewpoint)

def update_visibility():
    visibility_data.config(text=str(data1["current"]["visibility"]) + " meter")
    visibility_data.after(100,update_visibility)

def convert_time(timestamp):
    return datetime.fromtimestamp(timestamp).strftime("%I:%M %p")


canvas.place(x = 0, y = 0)

get_Weather()

canvas.create_rectangle(
    715.0,
    0.0,
    1035.0,
    665.0,
    fill="#0F0C29",
    outline="")

canvas.create_text(
    126.0,
    86.0,
    anchor="nw",
    text="Today Overview",
    fill="#000000",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_rectangle(
    10.0,
    125.0,
    706.0,
    658.0,
    fill="#0575E6",
    outline="")

canvas.create_rectangle(
    10.0,
    15.0,
    100.0,
    105.0,
    fill="#B4D2FF",
    outline="")

canvas.create_rectangle(
    759.0,
    143.0,
    831.0,
    202.0,
    fill="#000000",
    outline="")


canvas.create_text(
    735.0,
    73.0,
    anchor="nw",
    text="Telangana, India",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)


digital_clock_lbl=Label(window,text="00.00",font=("ds-digital",15),bg="#0F0C29",fg="#FFFFFF")
digital_clock_lbl.place(x=930,y=35)
update_clock()

'''canvas.create_text(
    941.0,
    35.0,
    anchor="nw",
    text="12:00 am",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

canvas.create_rectangle(
    747.0,
    125.0,
    853.0,
    220.0,
    fill="#FFFFFF",
    outline="")

temperature_data = Label(text=str(floor(data1["current"]["temp"])) + " ᴼ C", font=("Inter SemiBold",15,"bold"), bg="#0F0C29", fg="#FFFFFF")
temperature_data.place(x=930,y=135)

'''canvas.create_text(
    928.0,
    134.0,
    anchor="nw",
    text="27o C",
    fill="#FFFFFF",
    font=("Inter", 24 * -1)
)'''

weather_desc_data = Label(text=data1["current"]["weather"][0]["main"].title(), font=("Inter SemiBold",20,"bold"), bg="#0F0C29", fg="#FFFFFF")
weather_desc_data.place(x=920,y=170)
update_weather_desc()

'''canvas.create_text(
    917.0,
    172.0,
    anchor="nw",
    text="Cloudy",
    fill="#FFFFFF",
    font=("Inter", 24 * -1)
)'''

canvas.create_rectangle(
    742.0,
    230.0,
    1007.0,
    231.0,
    fill="#D2AD2B",
    outline="")

date = datetime.now()
date_time_lbl = Label(window, text=f"{date:%d / %m / %Y \n%A}", font=("Inter SemiBold", 10), bg="#FFFFFF", fg="#000000")
date_time_lbl.place(x=600, y=25)
update_date()

'''canvas.create_text(
    566.0,
    23.0,
    anchor="nw",
    text="January 01 2022\n",
    fill="#000000",
    font=("Inter SemiBold", 16 * -1)
)'''

canvas.create_rectangle(
    568.0,
    46.0,
    706.0,
    47.01458740234375,
    fill="#000000",
    outline="")

Wind_speed_lbl = Label(window, text="Wind Speed", font= ("Inter SemiBold",12,"bold"), bg="#0575E6", fg="#FFFFFF")
Wind_speed_lbl.place(x=150,y=180)

'''canvas.create_text(
    147.0,
    176.0,
    anchor="nw",
    text="Wind Speed",
    fill="#FFFFFF",
    font=("Inter SemiBold", 16 * -1)
)'''

wind_speed_data= Label(text= str(data1["current"]["wind_speed"]) + " meter/sec", font=("Inter SemiBold",12,"bold"), bg="#0575E6", fg="#FFFFFF")
wind_speed_data.place(x=150,y=210)
update_wind_speed()

'''canvas.create_text(
    155.0,
    207.0,
    anchor="nw",
    text="12 KMPH",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)'''

humidity_lbl = Label(window, text="Humidity", font= ("Inter SemiBold",12, "bold"), bg="#0575E6", fg="#FFFFFF")
humidity_lbl.place(x=450,y=180)

'''canvas.create_text(
    449.0,
    176.0,
    anchor="nw",
    text="Humidity",
    fill="#FFFFFF",
    font=("Inter SemiBold", 16 * -1)
)'''


humidity_data = Label(text=str(data1["current"]["humidity"])+ "%", font=("Inter Regular",12,"bold"), bg="#0575E6", fg="#FFFFFF")
humidity_data.place(x=450,y=210)
update_humidity()

'''canvas.create_text(
    476.0,
    210.0,
    anchor="nw",
    text="98%",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)'''

pressure_lbl = Label(window, text="Pressure", font=("Inter Regular",12,"bold"), bg="#0575E6", fg="#FFFFFF")
pressure_lbl.place(x=450,y=290)

'''canvas.create_text(
    455.0,
    286.0,
    anchor="nw",
    text="Pressure",
    fill="#FFFFFF",
    font=("Inter SemiBold", 16 * -1)
)'''

pressure_data = Label(window, text=str(data1["current"]["pressure"]) + " hPa",font=("Inter Regular",12,"bold"), bg="#0575E6", fg="#FFFFFF")
pressure_data.place(x=450,y=320)
update_pressure()


'''canvas.create_text(
    474.0,
    318.0,
    anchor="nw",
    text="120 Pa",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)'''

uvi_lbl = Label(window, text="UVI", font=("Inter Regular",12,"bold"), bg="#0575E6", fg="#FFFFFF")
uvi_lbl.place(x=150,y=290)

'''canvas.create_text(
    144.0,
    287.0,
    anchor="nw",
    text="UVI",
    fill="#FFFFFF",
    font=("Inter SemiBold", 16 * -1)
)'''

uvi_data = Label(window, text=data1["current"]["uvi"],font=("Inter Regular",12,"bold"), bg="#0575E6", fg="#FFFFFF")
uvi_data.place(x=150,y=320)
update_uvi()

'''canvas.create_text(
    161.0,
    318.0,
    anchor="nw",
    text="3",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)'''

dew_point_label = Label(window, text="Dew Point", font=("Inter Regular", 12, "bold"), bg="#0575E6", fg="#FFFFFF")
dew_point_label.place(x=150, y=390)

'''canvas.create_text(
    145.0,
    392.0,
    anchor="nw",
    text="Dew Point",
    fill="#FFFFFF",
    font=("Inter SemiBold", 16 * -1)
)'''

dew_point_data = Label(window, text=str(data1["current"]["dew_point"]) + " C", font=("Inter Regular", 12, "bold"), bg="#0575E6", fg="#FFFFFF")
dew_point_data.place(x=150, y=430)
update_dewpoint()

'''canvas.create_text(
    164.0,
    431.0,
    anchor="nw",
    text="23.98",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)'''

visibility_label = Label(window, text="Visibility", font=("Inter Regular", 12, "bold"), bg="#0575E6", fg="#FFFFFF")
visibility_label.place(x=450, y=390)

'''canvas.create_text(
    450.0,
    393.0,
    anchor="nw",
    text="Visibility",
    fill="#FFFFFF",
    font=("Inter SemiBold", 16 * -1)
)'''

visibility_data = Label(window, text=str(data1["current"]["visibility"]) + " meter", font=("Inter Regular", 12, "bold"), bg="#0575E6", fg="#FFFFFF")
visibility_data.place(x=450, y=430)
update_visibility()

'''canvas.create_text(
    468.0,
    431.0,
    anchor="nw",
    text="200",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)'''

canvas.create_rectangle(
    121.0,
    104.98539733886719,
    260.99989318847656,
    107.0,
    fill="#000000",
    outline="")

canvas.create_text(
    744.0,
    392.0,
    anchor="nw",
    text="Wednesday",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    905.0,
    395.0,
    anchor="nw",
    text="27o C",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    911.0,
    417.0,
    anchor="nw",
    text="Thunderstorm",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    738.0,
    332.0,
    anchor="nw",
    text="Tomorrow",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    906.0,
    330.0,
    anchor="nw",
    text="27o C",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    905.0,
    357.0,
    anchor="nw",
    text="Mist",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    728.0,
    268.0,
    anchor="nw",
    text="Today",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    914.0,
    267.0,
    anchor="nw",
    text="27o C",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    906.0,
    290.0,
    anchor="nw",
    text="Rainy",
    fill="#FFFFFF",
    font=("Inter Regular", 16 * -1)
)

canvas.create_rectangle(
    735.0,
    472.0,
    1024.0,
    549.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    763.0,
    511.0,
    anchor="nw",
    text="4:00 am",
    fill="#000000",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_rectangle(
    928.0,
    480.0,
    999.0,
    537.0,
    fill="#D0B146",
    outline="")

canvas.create_rectangle(
    735.0,
    566.0,
    1024.0,
    643.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    752.0,
    578.0,
    anchor="nw",
    text="Sunset",
    fill="#000000",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    776.0,
    605.0,
    anchor="nw",
    text="6:00 pm",
    fill="#000000",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_rectangle(
    928.0,
    578.0,
    999.0,
    635.0,
    fill="#D0B146",
    outline="")

canvas.create_rectangle(
    765.1012573242188,
    152.72373962402344,
    824.9174499511719,
    192.3636932373047,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    775.77001953125,
    166.37875366210938,
    811.5600280761719,
    174.98292541503906,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    807.0,
    155.29165649414062,
    824.9100036621094,
    170.60708618164062,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    23.0,
    479.0,
    696.0,
    643.0,
    fill="#41295A",
    outline="")

hour_1 = Label(window, text=convert_time(data1["hourly"][0]["dt"]), font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_1.place(x=55, y=510)

'''canvas.create_text(
    55.0,
    510.0,
    anchor="nw",
    text="01:00",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_2 = Label(window, text=convert_time(data1["hourly"][1]["dt"]), font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_2.place(x=170, y=510)

'''canvas.create_text(
    170.0,
    510.0,
    anchor="nw",
    text="02:00",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_3 = Label(window, text=convert_time(data1["hourly"][2]["dt"]), font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_3.place(x=285, y=510)

'''canvas.create_text(
    285.0,
    510.0,
    anchor="nw",
    text="03:00",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_4 = Label(window, text=convert_time(data1["hourly"][3]["dt"]), font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_4.place(x=390, y=510)

'''canvas.create_text(
    390.0,
    510.0,
    anchor="nw",
    text="04:00",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_5 = Label(window, text=convert_time(data1["hourly"][4]["dt"]), font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_5.place(x=495, y=510)

'''canvas.create_text(
    495.0,
    510.0,
    anchor="nw",
    text="05:00",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_6 = Label(window, text=convert_time(data1["hourly"][5]["dt"]), font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_6.place(x=600, y=510)

'''canvas.create_text(
    600.0,
    510.0,
    anchor="nw",
    text="06:00",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_1_temp = Label(window, text=str(floor(data1["hourly"][0]["temp"])) + " ᴼ C", font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_1_temp.place(x=55, y=550)

'''canvas.create_text(
    55.0,
    550.0,
    anchor="nw",
    text="20o C",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_2_temp = Label(window, text=str(floor(data1["hourly"][1]["temp"])) + " ᴼ C", font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_2_temp.place(x=170, y=550)

'''canvas.create_text(
    170.0,
    550.0,
    anchor="nw",
    text="21o C",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_3_temp = Label(window, text=str(floor(data1["hourly"][2]["temp"])) + " ᴼ C", font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_3_temp.place(x=285, y=550)

'''canvas.create_text(
    285.0,
    550.0,
    anchor="nw",
    text="22o C",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_4_temp = Label(window, text=str(floor(data1["hourly"][3]["temp"])) + " ᴼ C", font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_4_temp.place(x=390, y=550)

'''canvas.create_text(
    390.0,
    550.0,
    anchor="nw",
    text="23o C",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_5_temp = Label(window, text=str(floor(data1["hourly"][4]["temp"])) + " ᴼ C", font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_5_temp.place(x=495, y=550)

'''canvas.create_text(
    495.0,
    550.0,
    anchor="nw",
    text="24o C",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_6_temp = Label(window, text=str(floor(data1["hourly"][5]["temp"])) + " ᴼ C", font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_6_temp.place(x=600, y=550)

'''canvas.create_text(
    600.0,
    550.0,
    anchor="nw",
    text="25o C",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_1_desc = Label(window, text=data1["hourly"][0]["weather"][0]["main"], font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_1_desc.place(x=55, y=590)

'''canvas.create_text(
    45.0,
    590.0,
    anchor="nw",
    text="Cloudy1",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_2_desc = Label(window, text=data1["hourly"][1]["weather"][0]["main"], font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_2_desc.place(x=170, y=590)

'''canvas.create_text(
    160.0,
    590.0,
    anchor="nw",
    text="Cloudy2",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_3_desc = Label(window, text=data1["hourly"][2]["weather"][0]["main"], font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_3_desc.place(x=285, y=590)

'''canvas.create_text(
    270.0,
    590.0,
    anchor="nw",
    text="Cloudy3",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_4_desc = Label(window, text=data1["hourly"][3]["weather"][0]["main"], font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_4_desc.place(x=390, y=590)

'''canvas.create_text(
    381.0,
    590.0,
    anchor="nw",
    text="Cloudy4",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_5_desc = Label(window, text=data1["hourly"][4]["weather"][0]["main"], font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_5_desc.place(x=495, y=590)

'''canvas.create_text(
    480.0,
    590.0,
    anchor="nw",
    text="Cloudy5",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

hour_6_desc = Label(window, text=data1["hourly"][5]["weather"][0]["main"], font=("Inter Regular", 12, "bold"), bg="#41295A", fg="#FFFFFF")
hour_6_desc.place(x=600, y=590)

'''canvas.create_text(
    590.0,
    590.0,
    anchor="nw",
    text="Cloudy6",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)'''

canvas.create_text(
    751.0,
    484.0,
    anchor="nw",
    text="Sunrise",
    fill="#000000",
    font=("Inter Regular", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
